FROM gradle:8-jdk17 AS build
WORKDIR /app
COPY . .
RUN chmod +x gradlew
RUN ./gradlew bootWar

FROM azul/zulu-openjdk:17-latest
VOLUME /tmp
COPY --from=build /app/build/libs/*.war app.war
CMD ["java", "-jar", "/app.war"]